# The name of the app. Must be unique within a project.
name: webh

# The type of the application to build
type: 'nodejs:16'

# The size of the persistent disk of the application (in MB)
disk: 512

# Your app's configuration when it's exposed to the web.
web:
    commands:
        start: NODE_ENV=production npm run start
mounts:
    'log':
        source: local
        source_path: "log/"
